---
{{ if .Values.unbound.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-pihole-conf
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pi-hole.conf: |
    server:
        # Include defaults, then override
        include: /etc/unbound/unbound.conf

        # If no logfile is specified, syslog is used
        # logfile: "/var/log/unbound/unbound.log"
        # The verbosity number, level 0 means no verbosity, only errors.
        # Level 1 gives operational information.
        # Level 2 gives detailed operational information.
        # Level 3 gives query level information, output per query.
        # Level 4 gives algorithm level information.
        # Level 5 logs client identification for cache misses.
        verbosity: 0

        interface: 127.0.0.1
        port: 5053
{{ end }}
